services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    shm_size: 4gb
    networks:
      - subtitle-network
    cpuset: "0-4"
    environment:
      - TZ=Asia/Shanghai  # 添加这行
    deploy:
      resources:
        limits:
          cpus: '5.0'

  nas-subtitle:
    build: .
    container_name: nas-subtitle
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./data:/data
      - /vol2/1000/MyCloud/Downloads/迅雷:/media/movies
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    shm_size: 4gb
    networks:
      - subtitle-network
    depends_on:
      - ollama
    cpuset: "0-4"
    deploy:
      resources:
        limits:
          cpus: '5.0'

networks:
  subtitle-network:
    driver: bridge