services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    shm_size: 4gb            # 限制最大使用4G内存，可根据需求修改或注释
    networks:
      - subtitle-network
    cpuset: "0-4"           # 绑定核心数，可根据需求修改或注释
    environment:
      - TZ=Asia/Shanghai  # 添加这行
    deploy:                # 最多使用核心数，可根据需求修改或注释
      resources:
        limits:
          cpus: '5.0'

  nas-subtitle:
    build: .
    container_name: nas-submaster
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./data:/data
      - /your/media/path:/media/movies  # 修改成你自己的媒体库地址
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    shm_size: 4gb   # 限制最大使用4G内存，可根据需求修改或注释
    networks:
      - subtitle-network
    depends_on:
      - ollama
    cpuset: "0-4"  # 绑定核心数，可根据需求修改或注释
    deploy:         # 最多使用核心数，可根据需求修改或注释
      resources:
        limits:
          cpus: '5.0'

networks:
  subtitle-network:
    driver: bridge
